<?php

$lang = $_GET['lang'] ?? $_SESSION['lang'] ?? 'PL';
$_SESSION['lang'] = strtoupper($lang);
$lang = $_SESSION['lang'];

$translations = [
    'PL' => [
        'home' => 'Strona główna',
        'login' => 'Zaloguj się',
        'register' => 'Rejestracja',
        'dashboard' => 'Dashboard',
        'map' => 'Mapa',
        'logout' => 'Wyloguj się',
        'welcome' => 'Witaj na 446CLUSTER!',
        'pmr_platform' => 'Platforma komunikacji PMR dla Polskich operatorów',
        'live_traffic' => 'Live traffic',
        'add_spot' => 'Dodaj spot',
        'my_profile_link' => 'Mój profil',
        'add_spot_link' => 'Dodaj spot',
        'my_spots_link' => 'Moje spoty',
        'statistics' => 'Statystyka',
        'stats' => 'Statystyka',
        'spots_today' => 'Spotów dzisiaj:',
        'spots_month' => 'Spotów w tym miesiącu:',
        'this_month' => 'w tym miesiącu:',
        'operators_today' => 'Operatorów dzisiaj:',
        'channel_day' => 'Kanał dnia:',
        'channel_of_day' => 'Kanał dnia:',
        'last_spot' => 'Ostatni spot:',
        'quick_actions' => 'Szybkie akcje',
        'my_recent_spots' => 'Moje ostatnie spoty',
        'my_profile' => 'Mój profil',
        'my_spots' => 'Moje spoty',
        'no_spots' => 'Brak spotów',
        'manage_all' => 'Zarządzaj wszystkimi',
        'live_spots' => 'Live spoty',
        'auto_refresh_on' => 'AUTO REFRESH ON',
        'auto_refresh_off' => 'AUTO REFRESH OFF',
        'utc' => 'UTC',
        'operator' => 'OPERATOR',
        'correspondent' => 'KORESPONDENT',
        'ch' => 'CH',
        'mode' => 'MODE',
        'from' => 'FROM',
        'to' => 'TO',
        'km' => 'KM',
        'comment' => 'COMMENT',
        'added' => 'ADDED',
        'none' => 'Brak',
    ],
    'EN' => [
        'home' => 'Home',
        'login' => 'Login',
        'register' => 'Register',
        'dashboard' => 'Dashboard',
        'map' => 'Map',
        'logout' => 'Logout',
        'welcome' => 'Welcome to 446CLUSTER!',
        'pmr_platform' => 'PMR communication platform for Polish operators',
        'live_traffic' => 'Live traffic',
        'add_spot' => 'Add spot',
        'my_profile_link' => 'My profile',
        'add_spot_link' => 'Add spot',
        'my_spots_link' => 'My spots',
        'statistics' => 'Statistics',
        'stats' => 'Statistics',
        'spots_today' => 'Spots today:',
        'spots_month' => 'Spots this month:',
        'this_month' => 'this month:',
        'operators_today' => 'Operators today:',
        'channel_day' => 'Channel of the day:',
        'channel_of_day' => 'Channel of the day:',
        'last_spot' => 'Last spot:',
        'quick_actions' => 'Quick actions',
        'my_recent_spots' => 'My recent spots',
        'my_profile' => 'My profile',
        'my_spots' => 'My spots',
        'no_spots' => 'No spots yet',
        'manage_all' => 'Manage all',
        'live_spots' => 'Live spots',
        'auto_refresh_on' => 'AUTO REFRESH ON',
        'auto_refresh_off' => 'AUTO REFRESH OFF',
        'utc' => 'UTC',
        'operator' => 'OPERATOR',
        'correspondent' => 'CORRESPONDENT',
        'ch' => 'CH',
        'mode' => 'MODE',
        'from' => 'FROM',
        'to' => 'TO',
        'km' => 'KM',
        'comment' => 'COMMENT',
        'added' => 'ADDED',
        'none' => 'None',
    ],
];

function t($key) {
    global $lang, $translations;
    return $translations[$lang][$key] ?? $key;
}

?>
